/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface PunksDNAInterface extends utils.Interface {
  functions: {
    "_getDNASection(uint256,uint8)": FunctionFragment;
    "deterministicPseudoRandomDNA(uint256,address)": FunctionFragment;
    "getAccessoriesType(uint256)": FunctionFragment;
    "getClotheColor(uint256)": FunctionFragment;
    "getClotheType(uint256)": FunctionFragment;
    "getEyeBrowType(uint256)": FunctionFragment;
    "getEyeType(uint256)": FunctionFragment;
    "getFacialHairColor(uint256)": FunctionFragment;
    "getFacialHairType(uint256)": FunctionFragment;
    "getGraphicType(uint256)": FunctionFragment;
    "getHairColor(uint256)": FunctionFragment;
    "getHatColor(uint256)": FunctionFragment;
    "getMouthType(uint256)": FunctionFragment;
    "getSkinColor(uint256)": FunctionFragment;
    "getTopType(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_getDNASection"
      | "deterministicPseudoRandomDNA"
      | "getAccessoriesType"
      | "getClotheColor"
      | "getClotheType"
      | "getEyeBrowType"
      | "getEyeType"
      | "getFacialHairColor"
      | "getFacialHairType"
      | "getGraphicType"
      | "getHairColor"
      | "getHatColor"
      | "getMouthType"
      | "getSkinColor"
      | "getTopType"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_getDNASection",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "deterministicPseudoRandomDNA",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessoriesType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getClotheColor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getClotheType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEyeBrowType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEyeType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacialHairColor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacialHairType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getGraphicType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHairColor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHatColor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMouthType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSkinColor",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "_getDNASection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deterministicPseudoRandomDNA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessoriesType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClotheColor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClotheType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEyeBrowType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEyeType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFacialHairColor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacialHairType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGraphicType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHairColor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHatColor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMouthType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSkinColor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTopType", data: BytesLike): Result;

  events: {};
}

export interface PunksDNA extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PunksDNAInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _getDNASection(
      _dna: PromiseOrValue<BigNumberish>,
      _rigthDiscard: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    deterministicPseudoRandomDNA(
      _tokenId: PromiseOrValue<BigNumberish>,
      _minter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAccessoriesType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getClotheColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getClotheType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getEyeBrowType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getEyeType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getFacialHairColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getFacialHairType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getGraphicType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getHairColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getHatColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMouthType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getSkinColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTopType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  _getDNASection(
    _dna: PromiseOrValue<BigNumberish>,
    _rigthDiscard: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  deterministicPseudoRandomDNA(
    _tokenId: PromiseOrValue<BigNumberish>,
    _minter: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAccessoriesType(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getClotheColor(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getClotheType(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getEyeBrowType(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getEyeType(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getFacialHairColor(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getFacialHairType(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getGraphicType(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getHairColor(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getHatColor(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getMouthType(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getSkinColor(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getTopType(
    _dna: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    _getDNASection(
      _dna: PromiseOrValue<BigNumberish>,
      _rigthDiscard: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    deterministicPseudoRandomDNA(
      _tokenId: PromiseOrValue<BigNumberish>,
      _minter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccessoriesType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getClotheColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getClotheType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getEyeBrowType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getEyeType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getFacialHairColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getFacialHairType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getGraphicType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getHairColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getHatColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getMouthType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getSkinColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getTopType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    _getDNASection(
      _dna: PromiseOrValue<BigNumberish>,
      _rigthDiscard: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deterministicPseudoRandomDNA(
      _tokenId: PromiseOrValue<BigNumberish>,
      _minter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccessoriesType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClotheColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClotheType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEyeBrowType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEyeType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacialHairColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFacialHairType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGraphicType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHairColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHatColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMouthType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSkinColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTopType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _getDNASection(
      _dna: PromiseOrValue<BigNumberish>,
      _rigthDiscard: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deterministicPseudoRandomDNA(
      _tokenId: PromiseOrValue<BigNumberish>,
      _minter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccessoriesType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClotheColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClotheType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEyeBrowType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEyeType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacialHairColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFacialHairType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGraphicType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHairColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHatColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMouthType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSkinColor(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTopType(
      _dna: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
