/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ExamplePunks__factory } from "./ExamplePunks__factory";
export { PunksDNA__factory } from "./PunksDNA__factory";
